#!/usr/bin/env python3
"""Generate an LVGL 8 bitmap font (lv_font_fmt_txt, 4 bpp) from a TTF with Pillow.

A stand-in for lv_font_conv (which needs node) for the few large glyphs the
UI needs.  Only a contiguous ASCII range is supported, no kerning.

    python tools/gen_font.py --ttf Montserrat-Medium.ttf --size 72 \
        --chars "0123456789-" --name lv_font_montserrat_72_digits \
        -o src/ui/font_montserrat_72_digits.c
"""
import argparse
from PIL import Image, ImageDraw, ImageFont


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--size", type=int, required=True, help="em size in px")
    ap.add_argument("--chars", required=True, help="contiguous or not; sparse map is emitted")
    ap.add_argument("--name", required=True)
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()

    font = ImageFont.truetype(a.ttf, a.size)
    ascent, descent = font.getmetrics()
    chars = sorted(set(a.chars), key=ord)

    bitmap = bytearray()
    dsc = [dict(idx=0, adv=0, w=0, h=0, ox=0, oy=0)]  # glyph 0 = reserved
    comments = ["    /* glyph 0: reserved */"]
    for ch in chars:
        # Render on a generous canvas and take the tight ink box; Pillow's
        # getbbox() is not tight.  Anchor 'la': baseline sits at y = ascent.
        pad = a.size
        canvas = Image.new("L", (3 * a.size, 3 * a.size), 0)
        ImageDraw.Draw(canvas).text((pad, pad), ch, font=font, fill=255)
        ink = canvas.getbbox()
        if ink is None:
            ink = (pad, pad, pad + 1, pad + 1)
        left, top, right, bottom = ink[0] - pad, ink[1] - pad, ink[2] - pad, ink[3] - pad
        w, h = right - left, bottom - top
        img = canvas.crop(ink)
        px = img.load()
        # 4 bpp, MSB first, bit stream continuous across rows, byte-padded per glyph
        nib = []
        for y in range(h):
            for x in range(w):
                nib.append(px[x, y] >> 4)
        if len(nib) % 2:
            nib.append(0)
        start = len(bitmap)
        for i in range(0, len(nib), 2):
            bitmap.append((nib[i] << 4) | nib[i + 1])
        dsc.append(dict(idx=start, adv=round(font.getlength(ch) * 16), w=w, h=h,
                        ox=left, oy=ascent - bottom))
        comments.append(f"    /* U+{ord(ch):04X} \"{ch}\" */")

    # Match lv_font_conv's Montserrat proportions so it sits like the built-ins.
    line_height = round(a.size * 1.125)
    base_line = round(a.size * 0.21)

    lines = []
    lines.append(f"/* Generated by tools/gen_font.py: {a.ttf} size {a.size} px, 4 bpp, chars {a.chars!r} */")
    lines.append("#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n#include \"lvgl.h\"\n#else\n#include \"lvgl/lvgl.h\"\n#endif\n")
    lines.append("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
    # emit per-glyph chunks with comments
    for gi in range(1, len(dsc)):
        s = dsc[gi]["idx"]
        e = dsc[gi + 1]["idx"] if gi + 1 < len(dsc) else len(bitmap)
        lines.append(comments[gi])
        chunk = bitmap[s:e]
        for i in range(0, len(chunk), 16):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk[i:i + 16]) + ",")
        lines.append("")
    lines.append("};\n")

    lines.append("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    for d in dsc:
        lines.append(f"    {{.bitmap_index = {d['idx']}, .adv_w = {d['adv']}, .box_w = {d['w']}, "
                     f".box_h = {d['h']}, .ofs_x = {d['ox']}, .ofs_y = {d['oy']}}},")
    lines.append("};\n")

    codes = [ord(c) for c in chars]
    lines.append("static const uint16_t unicode_list_0[] = {" +
                 ", ".join(f"0x{c - codes[0]:x}" for c in codes) + "};\n")
    lines.append("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    lines.append(f"    {{.range_start = {codes[0]}, .range_length = {codes[-1] - codes[0] + 1}, .glyph_id_start = 1,")
    lines.append(f"     .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL, .list_length = {len(codes)}, "
                 f".type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}},")
    lines.append("};\n")

    lines.append("static lv_font_fmt_txt_glyph_cache_t cache;")
    lines.append("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    lines.append("    .glyph_bitmap = glyph_bitmap, .glyph_dsc = glyph_dsc, .cmaps = cmaps,")
    lines.append("    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = 1, .bpp = 4, .kern_classes = 0,")
    lines.append("    .bitmap_format = 0, .cache = &cache};\n")
    lines.append(f"const lv_font_t {a.name} = {{")
    lines.append("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    lines.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    lines.append(f"    .line_height = {line_height}, .base_line = {base_line},")
    lines.append("    .subpx = LV_FONT_SUBPX_NONE, .underline_position = -4, .underline_thickness = 3,")
    lines.append("    .dsc = &font_dsc};")

    with open(a.out, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{a.out}: {len(chars)} glyphs, {len(bitmap)} bytes bitmap, line_height {line_height}, base_line {base_line}")


if __name__ == "__main__":
    main()
